version: '3.8'
services:
  app:
    build:
      context: . # Context is the monorepo root
      dockerfile: dockerfiles/Dockerfile.app
    volumes:
      - ./packages/app/src:/usr/src/app/packages/app/src
      - ./packages/app/.next:/usr/src/app/packages/app/.next
      - ./packages/libs:/usr/src/app/packages/libs
    environment:
      DATABASE_URL: 'postgresql://user:password@db:5432/mono'
    ports:
      - '3000:3000'
    depends_on: 
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mono
    ports:
      - '5432:5432'
